default:
  image: registry.gitlab.cc-asp.fraunhofer.de/cormier_students/docker-images/ubuntu_22.04:iv.visualizer.dev
  tags:
  - vid

stages:
  - style_check
  - build
  #- test
  - docs

variables:
  BUILD_DIR: build
  PROTOBUF_VERSION: "25.2"
  DEBIAN_FRONTEND: noninteractive 
  GIT_SUBMODULE_STRATEGY: recursive

style_check:
  stage: style_check
  script:
    - clang-format --version
    - clang-tidy --version
    #- bash scripts/style_check.sh

build:
  stage: build
  script:
    - bash build.sh 
  artifacts: 
    paths:
      - build

#test:
  #stage: test
  #script:
   # -  cd ${BUILD_DIR}/test
    #-  ./IV_VISUALIZER_test
  #dependencies:
   # - build

pages:
  stage: docs
  script:
  - doxygen Doxyfile
  - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
